### PR TITLE
Fix -Wunreachable-code-aggressive.

### PR DESCRIPTION
**Pull request by pkasting**
Bug: chromium:1066980

### CODE REVIEW

**Comment by kenrussell** [comment]
To be clear: this is affecting Chromium's build because this repository is built as part of the performance tests. See https://crbug.com/1066980 .

**Comment by kenrussell** [comment]
@afrantzis could you please review this? Thank you in advance.

**Review by jessebarker — APPROVED** [review]
LGTM

**Comment by kenrussell** [comment]
Thanks @jessebarker for your review! Could you also please help us merge this?

**Comment by jessebarker** [comment]
> Thanks @jessebarker for your review! Could you also please help us merge this?

There you go!  @afrantzis hopefully I didn't miss anything in the workflow checks (all the automatic triggered stuff passed).

**Comment by afrantzis** [comment]
@kenrussell @jessebarker LGTM. Thanks!

**Pull request merged**
