### PR TITLE
Build: Use the build system wayland-scanner on meson

### PR DESCRIPTION
**Pull request by afrantzis**
Fixes cross-compilation of glmark2 with meson.

### CODE REVIEW

**Comment by afrantzis** [comment]
@ffontaine

**Comment by ffontaine** [comment]
Thanks, I forgot to send this PR.

**Comment by afrantzis** [comment]
No worries, thanks for looking into this! I have marked you as the author (since you proposed the change in a comment of the previous PR), let me know if that's OK.

**Comment by ffontaine** [comment]
Sure, it's fine.

**Pull request merged**
