### PR TITLE
Retry opening a DRM driver using modules list if GetResources fails

### PR DESCRIPTION
**Pull request by superna9999**
Using the new Lima mesa driver and mainline Amlogic Meson DRM linux driver named "meson" (added to modules list with #53) glmark2 allways opens the wrong DRM driver (lima) and fails on drmGetResources().

The meson DRM driver is probed first and on card0, the lima driver is probed later on card1.
By default, the udev detection opens the card1 (which is valid) and tries to use it for init and fails on drmGetResources().
By removing the /dev/dri/card1 file makes it work since it tries the following device (card0) and works.

This patch retries with open_using_module_checking() also if drmGetResources() fails.

This does not fix the root issue, but better handles a bad detection with udev.

### CODE REVIEW

**Comment by afrantzis** [comment]
Hi! Thanks for the patch.

I am trying to understand why udev prefers the lima driver rather than the meson driver, but then the lima driver fails. Is this a deficiency in our udev scanning code or an issue with the driver?

If we go with your proposed approach of falling back to module checking, I think it would be cleaner to add a is_usable_drm_fd(int fd) function and call that in Init instead of just valid_fd(). The is_usable_drm_fd() function would call drmModeGetResources (or some other drm function) internally as a sanity check that this fd represents a usable drm device.

Perhaps as a future step we could try multiple devices returned from udev in order until we find one that succeeds (starting from what we think is the "main" one). In any case, the is_usable_drm_fd() approach outlined above should be fine for now (and your use case).

Adding support for the user to be able to override the used /dev/dri/cardN would also help with this, although it would have to be done manually by the user.

**Comment by superna9999** [comment]
@afrantzis thanks, I'll update with is_usable_drm_fd() then

For the override, it could be a real plus for development purpoeses

**Comment by Miouyouyou** [comment]
I'd also like to know why the udev check prefers the **lima** drived card to the **meson** one...

The udev checks are done in that order :

- Check for a primary GPU, looking for the "boot_vga" property in the sysfs entry of the DRM node.
- Take the first "non-virtual" DRM device.
- Use a virtual one, if any. 

My guess is that your lima card is detected as the primary GPU and has the "boot vga" flag

Does : `find /sys -iname "boot_vga"` returns something (beside permission errors) on your system ?

**Comment by mmind** [comment]
I've also run into this right now ;-) .

I think the main issue is, that card ordering (by probe order) and the order udev uses should always be expected to be random and in the lima- (or panfrost- or etnaviv-) case the GPU-driver is render-only so cannot drive an actual display but only hand over its buffer to a drm-device via prime.

But just skipping udev handling and falling to back to mechanism requiring manually adding each drm-driver also feels clumsy :-D .

I guess a better solution might be to actually try an throw-away GETRESOURCES before selecting the drm-device as usable?

**Comment by superna9999** [comment]
Well, it opens another question about systems with multiple display drm devices, we should be able to force a specific display device and bypass the autodetect.

**Comment by mmind** [comment]
I read a comment somewhere in the code, that this is a wishlist item :-)

**Comment by Miouyouyou** [comment]
Well, my initial commit was in the lines "Just add a --drm-device=/path/to/drm/node". However... it's a benchmarking tool that should be as automatic as possible, so the udev mechanism was implemented instead.
Now, benchmarking tools are for power users and power users can tinker, so I'll try to implement the manual option and send a pull request.

Still, if that were some game or 3D production software, is there a way to determine that a DRM node is render-only ? And, how can the program be sure that "it's the preferred node for OpenGL rendering on this system".
Is there a way to tag a DRM node as being "The preferred node for OpenGL programs" ? Or at least to determine which node is the most appropriate for that kind of task. I mean, some kind of Vulkan ways to determine which GPU is best fitted for the purpose.

**Comment by mmind** [comment]
@Miouyouyou please take a look at the bigger pull request I sent some hours ago, where I try to implement just that. So I guess all solutions make sense together, trying to guess first, falling back to the list and at any time allowing to specify a custom device node.

**Comment by superna9999** [comment]
Fixed by #73 
Thanks @mmind

**Pull request closed without merging**
