### PR TITLE
Fastlane and android icon for F-Droid release

### PR DESCRIPTION
**Pull request by paolo-caroni**
Hi,
as asked on the issude #116 I have added the fastlane structure and a icon for the android release.

I hope that you like it.
The icon it's "neded" because an app without icon is very ugly, but if you don't like it I can modify the logo.

Cheers,
Paolo

### CODE REVIEW

**Comment by afrantzis** [comment]
Hi Paolo! Thanks for all the great work. The icon looks great, too.

I wonder if the fastlane/ dir can live inside the android/ dir, or it needs to be at the root to be detected. Not a big deal, but I would like to contain all the android stuff in a single place if possible.

**Comment by IzzySoft** [comment]
@afrantzis Fastlane must be in the project root to be detected, sorry. If you really cannot live with that (which I hope is not the case), a fall-back would be using [Triple-T file structure](https://gitlab.com/snippets/1901490) instead. But if you don't need that extra complexity, Fastlane should be much easier to maintain.

@paolo-caroni structure looks good! @afrantzis might wish to add the per-release changelogs whenever making a new release, for "better promotion" :wink:

**Comment by paolo-caroni** [comment]
If I don't have misunderstood @afrantzis isn't really interested in promote android version of glmark2.
I think this benchmark is oriented more towards GNU / Linux (I use it on Debian) and perhaps MacOS X.
The change logs are already in the /NEWS file, i will add the information in the fastlane structure and make a different pull request when I've done.

**Comment by IzzySoft** [comment]
@paolo-caroni per-release changelogs would be "icing on the cake" – but they only make sense if kept up-to-date whenever a new version is released (i.e. they must be part of the corresponding tag).

**Comment by afrantzis** [comment]
@IzzySoft @paolo-caroni Ok, so let's leave the fastlane dir as it is.

I am fine with updating the release changelogs in fastlane also whenever a new release is made.

I also noticed that this PR introduces several screenshots that consume a couple of MBs of space. Could you please scale them down and/or remove some of them to reduce the storage consumption?

**Comment by paolo-caroni** [comment]
I have scaled alle the screenshots and removed the last one (my score).
I have also added the old changelogs, splitted for version number.
cheers, Paolo

**Comment by afrantzis** [comment]
Thanks! I have merged these changes in master. I reorganized the commits a bit, and also optimized the pngs to save a bit more space.

@paolo-caroni I hope to tag a new release soon (hopefully next week, if not this one). If you have the time, I will ping you in that PR to verify everything is fine for the F-Droid release.

**Comment by paolo-caroni** [comment]
Sure I will do that, maybe ping also @IzzySoft that is a maintainer of F-droid.

**Comment by IzzySoft** [comment]
Well, you'll see if everything turns up allright once the update got into the index, Paolo. If something looks weird then, ask me and I'll check.

**Pull request closed without merging**
